
class EnvironmentVariables:
    SERVER_ADDRESS = "COLEXT_SERVER_ADDRESS"
    CLIENT_ID = "COLEXT_CLIENT_ID"
    DEVICE_TYPE = "COLEXT_DEVICE_TYPE"
    NUM_CLIENTS = "COLEXT_N_CLIENTS"
    DATA_HOME_FOLDER = "COLEXT_DATA_HOME_FOLDER"
